name: Deploy to server
on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Play Ansible Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: ansible/playbook.yml
